"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://andriy.api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "/hyperMILL_Package/installation/HCNT_DOC.loc",
    "translation": "/hyperMILL_Package/installation/%file_name%.%locale%.%file_extension%"
  }
]
