"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_PERSONAL_TOKEN"
"base_url": "https://andriy.api.crowdin.com"
"preserve_hierarchy": true

files: 
  - "source": "/Application/Installation/HCNT_DOC.loc"
    "translation": "/Application/Installation/%file_name%.%locale%.loc"
