"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_PERSONAL_TOKEN"
"base_url": "https://andriy.api.crowdin.com"
"preserve_hierarchy": true

files: 
  - "source": "/en/messages.json"
    "translation": "/%two_letters_code%/%original_file_name%"
