name: Crowdin Upload and Download
on:
  push:
    branches: [ main ]
jobs:
  download_sources:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Crowdin download sources
        uses: crowdin/github-action@v1
        with: 
          upload_sources: false
          upload_translations: false
          download_translations: false
          create_pull_request: false
          command: 'download sources'
          command_args: '--config=crowdin.yml --reviewed'
          localization_branch_name: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_PERSONAL_TOKEN }}
