name: Crowdin Upload and Download
on:
#  push:
#    branches: [ main ]
  workflow_dispatch:
jobs:
  download_sources:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Crowdin download sources
        uses: crowdin/github-action@v2
        with: 
          upload_sources: true
          upload_translations: false
          download_translations: true
          create_pull_request: true
          pull_request_title: New Crowdin translations
          pull_request_body: New Crowdin pull request with translations
          pull_request_base_branch_name: main
          commit_message: New Crowdin translations by GitHub Action
          localization_branch_name: l10n_crowdin_translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_PERSONAL_TOKEN }}
